-- DROP DATABASE
DROP DATABASE IF EXISTS ecommerce_db;

-- CREATE DATABASE
CREATE DATABASE ecommerce_db;


CREATE TABLE Category(
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
category_name VARCHAR(30) NOT NULL
);


CREATE TABLE Product (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
product_name VARCHAR(30) NOT NULL,
price DECIMAL(6), NOT NULL,
stock INT UNSIGNED NOT NULL,
CONSTRAINT category_id INT FOREIGN KEY (category _id) REFERENCES category(id) ON DELETE CASCADE
);


CREATE TABLE Tag (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
tag_name VARCHAR(30) NOT NULL
);

CREATE TABLE ProductTag (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
product_id VARCHAR(30) NOT NULL
CONSTRAINT products_id INT FOREIGN KEY (product_id _id) REFERENCES products(id) ON DELETE CASCADE
tag_id INT UNSIGNED NOT NULL


